version: "3.1"
services:

  servizio_database_demo_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postgres_container_demo_app
    environment:
      POSTGRES_DB: progetto_demo_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'

  kafka:
    image: lensesio/fast-data-dev:latest
    container_name: kafka
    environment:
      SAMPLEDATA: 0
      RUNTESTS: 0
      ADV_HOST: 127.0.0.1
      CONNECT_HEAP: 1G
      CONNECTORS: elastic
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    ports:
      - "2181:2181"
      - "9092:9092"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"